move test to check-shell.yml

diff --git a/.github/workflows/check-shell.yml b/.github/workflows/check-shell.yml
--- a/.github/workflows/check-shell.yml
+++ b/.github/workflows/check-shell.yml
@@ -25,3 +25,31 @@ jobs:
       - run: nix develop --command graph --version
       - run: nix develop --command goldsky --version
 
+      # Run on macOS only
+      - name: Check tauri-shell
+        if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
+        run: |
+          nix develop .#tauri-shell -c bash -c '
+            # Bail if /usr/bin is not in the PATH
+            if echo "$PATH" | grep -qE "(^|:)/usr/bin(:|$)"; then
+              echo "/usr/bin is in the PATH, ...OK"
+            else
+              echo "did NOT find any /usr/bin in the PATH, aborting..."
+              exit 1
+            fi
+
+            # Bail if xcrun is in the PATH
+            if echo "$PATH" | grep -q "xcrun"; then
+              echo "found xcrun in the PATH, aborting..."
+              exit 1
+            else
+              echo "no xcrun detected in the PATH, ...OK"
+            fi
+
+            # Bail if DEVELOPER_DIR is set
+            if [ -z "${DEVELOPER_DIR+x}" ]; then
+              echo "The environment variable DEVELOPER_DIR is unset, ...OK"
+            else
+              echo "The environment variable DEVELOPER_DIR is not unset, aborting..."
+              exit 1
+            fi'
